// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v5.29.2
// source: email_verification.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "email_verification";

export interface VerifyEmailRequest {
  email: string;
  link: string;
}

export interface VerifyEmailResponse {
  message: string;
}

export const EMAIL_VERIFICATION_PACKAGE_NAME = "email_verification";

export interface EmailVerificationServiceClient {
  sendEmailVerificationLink(request: VerifyEmailRequest): Observable<VerifyEmailResponse>;
}

export interface EmailVerificationServiceController {
  sendEmailVerificationLink(
    request: VerifyEmailRequest,
  ): Promise<VerifyEmailResponse> | Observable<VerifyEmailResponse> | VerifyEmailResponse;
}

export function EmailVerificationServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["sendEmailVerificationLink"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("EmailVerificationService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("EmailVerificationService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const EMAIL_VERIFICATION_SERVICE_NAME = "EmailVerificationService";
